[project]
name = "razorpay-revenue-recovery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "dotenv>=0.9.9",
    "faker>=40.36.0",
    "fastmcp>=4.0.2",
    "google>=3.0.0",
    "groq>=1.7.0",
    "httpx>=0.28.1",
    "langgraph>=1.2.11",
    "loguru>=0.7.3",
    "lxml>=6.1.2",
    "markdown-it-py>=4.2.0",
    "nicegui>=3.16.0",
    "onnx>=1.22.0",
    "onnxruntime>=1.29.0",
    "onnxscript>=0.7.1",
    "openai>=3.5.0",
    "pandas>=3.0.5",
    "pinecone>=9.1.0",
    "pydantic>=2.13.4",
    "pyyaml>=6.0.3",
    "rank-bm25>=0.2.2",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=6.0.1",
    "torch>=2.13.0",
    "transformers>=5.16.1",
]
